export interface SymbolInfo { symbol: string; name: string }

// Common equities, ETFs, and indices for autosuggest
export const SYMBOL_CATALOG: SymbolInfo[] = [
  // Mega-cap tech
  { symbol: 'AAPL',  name: 'Apple' },
  { symbol: 'MSFT',  name: 'Microsoft' },
  { symbol: 'NVDA',  name: 'NVIDIA' },
  { symbol: 'GOOGL', name: 'Alphabet A' },
  { symbol: 'GOOG',  name: 'Alphabet C' },
  { symbol: 'AMZN',  name: 'Amazon' },
  { symbol: 'META',  name: 'Meta' },
  { symbol: 'TSLA',  name: 'Tesla' },
  { symbol: 'AVGO',  name: 'Broadcom' },
  { symbol: 'ORCL',  name: 'Oracle' },
  { symbol: 'CRM',   name: 'Salesforce' },
  { symbol: 'ADBE',  name: 'Adobe' },
  { symbol: 'AMD',   name: 'AMD' },
  { symbol: 'INTC',  name: 'Intel' },
  { symbol: 'QCOM',  name: 'Qualcomm' },
  { symbol: 'TXN',   name: 'Texas Instruments' },
  { symbol: 'MU',    name: 'Micron' },
  { symbol: 'AMAT',  name: 'Applied Materials' },
  { symbol: 'LRCX',  name: 'Lam Research' },
  { symbol: 'KLAC',  name: 'KLA Corp' },
  { symbol: 'SNPS',  name: 'Synopsys' },
  { symbol: 'CDNS',  name: 'Cadence' },
  { symbol: 'PANW',  name: 'Palo Alto Networks' },
  { symbol: 'CRWD',  name: 'CrowdStrike' },
  { symbol: 'FTNT',  name: 'Fortinet' },
  { symbol: 'NOW',   name: 'ServiceNow' },
  { symbol: 'INTU',  name: 'Intuit' },
  { symbol: 'WDAY',  name: 'Workday' },
  { symbol: 'SNOW',  name: 'Snowflake' },
  { symbol: 'PLTR',  name: 'Palantir' },
  { symbol: 'NET',   name: 'Cloudflare' },
  { symbol: 'DDOG',  name: 'Datadog' },
  { symbol: 'ZS',    name: 'Zscaler' },
  { symbol: 'MDB',   name: 'MongoDB' },
  { symbol: 'TEAM',  name: 'Atlassian' },
  { symbol: 'UBER',  name: 'Uber' },
  { symbol: 'LYFT',  name: 'Lyft' },
  { symbol: 'DASH',  name: 'DoorDash' },
  { symbol: 'ABNB',  name: 'Airbnb' },
  { symbol: 'SHOP',  name: 'Shopify' },
  { symbol: 'SQ',    name: 'Block' },
  { symbol: 'PYPL',  name: 'PayPal' },
  { symbol: 'V',     name: 'Visa' },
  { symbol: 'MA',    name: 'Mastercard' },
  { symbol: 'COIN',  name: 'Coinbase' },
  { symbol: 'HOOD',  name: 'Robinhood' },
  // Financials
  { symbol: 'JPM',   name: 'JPMorgan Chase' },
  { symbol: 'BAC',   name: 'Bank of America' },
  { symbol: 'WFC',   name: 'Wells Fargo' },
  { symbol: 'GS',    name: 'Goldman Sachs' },
  { symbol: 'MS',    name: 'Morgan Stanley' },
  { symbol: 'C',     name: 'Citigroup' },
  { symbol: 'BLK',   name: 'BlackRock' },
  { symbol: 'AXP',   name: 'American Express' },
  { symbol: 'SCHW',  name: 'Schwab' },
  { symbol: 'BRK-B', name: 'Berkshire B' },
  { symbol: 'BRK-A', name: 'Berkshire A' },
  { symbol: 'USB',   name: 'US Bancorp' },
  { symbol: 'PNC',   name: 'PNC Financial' },
  { symbol: 'TFC',   name: 'Truist' },
  { symbol: 'CME',   name: 'CME Group' },
  { symbol: 'ICE',   name: 'Intercontinental Exchange' },
  { symbol: 'SPGI',  name: 'S&P Global' },
  { symbol: 'MCO',   name: "Moody's" },
  // Healthcare
  { symbol: 'LLY',   name: 'Eli Lilly' },
  { symbol: 'UNH',   name: 'UnitedHealth' },
  { symbol: 'JNJ',   name: 'Johnson & Johnson' },
  { symbol: 'ABBV',  name: 'AbbVie' },
  { symbol: 'MRK',   name: 'Merck' },
  { symbol: 'PFE',   name: 'Pfizer' },
  { symbol: 'TMO',   name: 'Thermo Fisher' },
  { symbol: 'ABT',   name: 'Abbott' },
  { symbol: 'DHR',   name: 'Danaher' },
  { symbol: 'AMGN',  name: 'Amgen' },
  { symbol: 'GILD',  name: 'Gilead' },
  { symbol: 'BIIB',  name: 'Biogen' },
  { symbol: 'REGN',  name: 'Regeneron' },
  { symbol: 'VRTX',  name: 'Vertex' },
  { symbol: 'MRNA',  name: 'Moderna' },
  { symbol: 'CVS',   name: 'CVS Health' },
  { symbol: 'CI',    name: 'Cigna' },
  { symbol: 'HCA',   name: 'HCA Healthcare' },
  { symbol: 'ISRG',  name: 'Intuitive Surgical' },
  { symbol: 'BSX',   name: 'Boston Scientific' },
  // Consumer
  { symbol: 'AMZN',  name: 'Amazon' },
  { symbol: 'WMT',   name: 'Walmart' },
  { symbol: 'COST',  name: 'Costco' },
  { symbol: 'TGT',   name: 'Target' },
  { symbol: 'HD',    name: 'Home Depot' },
  { symbol: 'LOW',   name: "Lowe's" },
  { symbol: 'NKE',   name: 'Nike' },
  { symbol: 'SBUX',  name: 'Starbucks' },
  { symbol: 'MCD',   name: "McDonald's" },
  { symbol: 'CMG',   name: 'Chipotle' },
  { symbol: 'DPZ',   name: "Domino's" },
  { symbol: 'YUM',   name: 'Yum! Brands' },
  { symbol: 'DIS',   name: 'Disney' },
  { symbol: 'NFLX',  name: 'Netflix' },
  { symbol: 'CMCSA', name: 'Comcast' },
  { symbol: 'T',     name: 'AT&T' },
  { symbol: 'VZ',    name: 'Verizon' },
  { symbol: 'TMUS',  name: 'T-Mobile' },
  { symbol: 'PG',    name: 'Procter & Gamble' },
  { symbol: 'KO',    name: 'Coca-Cola' },
  { symbol: 'PEP',   name: 'PepsiCo' },
  { symbol: 'PM',    name: 'Philip Morris' },
  { symbol: 'MO',    name: 'Altria' },
  // Energy
  { symbol: 'XOM',   name: 'ExxonMobil' },
  { symbol: 'CVX',   name: 'Chevron' },
  { symbol: 'COP',   name: 'ConocoPhillips' },
  { symbol: 'SLB',   name: 'SLB (Schlumberger)' },
  { symbol: 'OXY',   name: 'Occidental' },
  { symbol: 'MPC',   name: 'Marathon Petroleum' },
  { symbol: 'PSX',   name: 'Phillips 66' },
  { symbol: 'VLO',   name: 'Valero' },
  { symbol: 'EOG',   name: 'EOG Resources' },
  { symbol: 'PXD',   name: 'Pioneer Natural' },
  // Industrials / Defense
  { symbol: 'CAT',   name: 'Caterpillar' },
  { symbol: 'DE',    name: 'Deere' },
  { symbol: 'BA',    name: 'Boeing' },
  { symbol: 'RTX',   name: 'RTX (Raytheon)' },
  { symbol: 'LMT',   name: 'Lockheed Martin' },
  { symbol: 'NOC',   name: 'Northrop Grumman' },
  { symbol: 'GD',    name: 'General Dynamics' },
  { symbol: 'GE',    name: 'GE Aerospace' },
  { symbol: 'HON',   name: 'Honeywell' },
  { symbol: 'MMM',   name: '3M' },
  { symbol: 'UPS',   name: 'UPS' },
  { symbol: 'FDX',   name: 'FedEx' },
  { symbol: 'CSX',   name: 'CSX' },
  { symbol: 'UNP',   name: 'Union Pacific' },
  { symbol: 'NSC',   name: 'Norfolk Southern' },
  // ETFs — Broad market
  { symbol: 'SPY',   name: 'SPDR S&P 500' },
  { symbol: 'QQQ',   name: 'Invesco QQQ (Nasdaq 100)' },
  { symbol: 'IWM',   name: 'iShares Russell 2000' },
  { symbol: 'DIA',   name: 'SPDR Dow Jones' },
  { symbol: 'VTI',   name: 'Vanguard Total Market' },
  { symbol: 'VOO',   name: 'Vanguard S&P 500' },
  { symbol: 'VEA',   name: 'Vanguard FTSE Dev Markets' },
  { symbol: 'VWO',   name: 'Vanguard FTSE Emerging' },
  { symbol: 'EFA',   name: 'iShares MSCI EAFE' },
  { symbol: 'EEM',   name: 'iShares MSCI Emerging' },
  { symbol: 'IVV',   name: 'iShares Core S&P 500' },
  // ETFs — Sector
  { symbol: 'XLK',   name: 'Technology Select SPDR' },
  { symbol: 'XLF',   name: 'Financial Select SPDR' },
  { symbol: 'XLV',   name: 'Health Care Select SPDR' },
  { symbol: 'XLE',   name: 'Energy Select SPDR' },
  { symbol: 'XLI',   name: 'Industrial Select SPDR' },
  { symbol: 'XLY',   name: 'Consumer Discret. SPDR' },
  { symbol: 'XLP',   name: 'Consumer Staples SPDR' },
  { symbol: 'XLU',   name: 'Utilities Select SPDR' },
  { symbol: 'XLB',   name: 'Materials Select SPDR' },
  { symbol: 'XLRE',  name: 'Real Estate Select SPDR' },
  { symbol: 'XLC',   name: 'Communication Services SPDR' },
  { symbol: 'SMH',   name: 'VanEck Semiconductor' },
  { symbol: 'SOXX',  name: 'iShares Semiconductor' },
  { symbol: 'IGV',   name: 'iShares Software' },
  { symbol: 'ARKK',  name: 'ARK Innovation' },
  { symbol: 'ARKG',  name: 'ARK Genomic Revolution' },
  // ETFs — Fixed income / Volatility / Commodity
  { symbol: 'TLT',   name: 'iShares 20+ Year Treasury' },
  { symbol: 'IEF',   name: 'iShares 7-10 Year Treasury' },
  { symbol: 'SHY',   name: 'iShares 1-3 Year Treasury' },
  { symbol: 'HYG',   name: 'iShares High Yield Bond' },
  { symbol: 'LQD',   name: 'iShares Investment Grade Bond' },
  { symbol: 'VXX',   name: 'iPath S&P 500 VIX ST' },
  { symbol: 'UVXY',  name: 'ProShares Ultra VIX ST' },
  { symbol: 'SVXY',  name: 'ProShares Short VIX ST' },
  { symbol: 'GLD',   name: 'SPDR Gold' },
  { symbol: 'IAU',   name: 'iShares Gold' },
  { symbol: 'SLV',   name: 'iShares Silver' },
  { symbol: 'GDX',   name: 'VanEck Gold Miners' },
  { symbol: 'GDXJ',  name: 'VanEck Junior Gold Miners' },
  { symbol: 'USO',   name: 'United States Oil Fund' },
  { symbol: 'UNG',   name: 'United States Natural Gas' },
  { symbol: 'DBO',   name: 'Invesco DB Oil' },
  // Leveraged ETFs
  { symbol: 'TQQQ',  name: 'ProShares UltraPro QQQ 3x' },
  { symbol: 'SQQQ',  name: 'ProShares UltraPro Short QQQ 3x' },
  { symbol: 'SPXL',  name: 'Direxion Daily S&P 500 Bull 3x' },
  { symbol: 'SPXS',  name: 'Direxion Daily S&P 500 Bear 3x' },
  { symbol: 'UPRO',  name: 'ProShares UltraPro S&P 500 3x' },
  { symbol: 'SOXL',  name: 'Direxion Daily Semi Bull 3x' },
  { symbol: 'SOXS',  name: 'Direxion Daily Semi Bear 3x' },
  { symbol: 'FNGU',  name: 'MicroSectors FANG+ 3x' },
  { symbol: 'FNGD',  name: 'MicroSectors FANG+ -3x' },
  { symbol: 'LABU',  name: 'Direxion Daily Bio Bull 3x' },
  { symbol: 'TECL',  name: 'Direxion Daily Tech Bull 3x' },
  { symbol: 'FAS',   name: 'Direxion Daily Fin Bull 3x' },
  { symbol: 'FAZ',   name: 'Direxion Daily Fin Bear 3x' },
  { symbol: 'TNA',   name: 'Direxion Daily SmallCap Bull 3x' },
  { symbol: 'TZA',   name: 'Direxion Daily SmallCap Bear 3x' },
  { symbol: 'ERX',   name: 'Direxion Daily Energy Bull 2x' },
  { symbol: 'NUGT',  name: 'Direxion Daily Gold Miners Bull 2x' },
  { symbol: 'JNUG',  name: 'Direxion Daily Jr Gold Bull 2x' },
  { symbol: 'BOIL',  name: 'ProShares Ultra Bloomberg Natural Gas 2x' },
  { symbol: 'KOLD',  name: 'ProShares UltraShort Bloomberg Natural Gas 2x' },
  // Crypto ETFs
  { symbol: 'IBIT',  name: 'iShares Bitcoin ETF' },
  { symbol: 'FBTC',  name: 'Fidelity Bitcoin ETF' },
  { symbol: 'ARKB',  name: 'ARK 21Shares Bitcoin ETF' },
  { symbol: 'GBTC',  name: 'Grayscale Bitcoin Trust' },
  { symbol: 'ETHA',  name: 'iShares Ethereum ETF' },
  // REITs
  { symbol: 'AMT',   name: 'American Tower' },
  { symbol: 'PLD',   name: 'Prologis' },
  { symbol: 'EQIX',  name: 'Equinix' },
  { symbol: 'CCI',   name: 'Crown Castle' },
  { symbol: 'SPG',   name: 'Simon Property' },
  { symbol: 'O',     name: 'Realty Income' },
  { symbol: 'WELL',  name: 'Welltower' },
  // Others commonly traded
  { symbol: 'TSM',   name: 'Taiwan Semiconductor' },
  { symbol: 'ASML',  name: 'ASML Holding' },
  { symbol: 'SAP',   name: 'SAP SE' },
  { symbol: 'NVO',   name: 'Novo Nordisk' },
  { symbol: 'BABA',  name: 'Alibaba' },
  { symbol: 'JD',    name: 'JD.com' },
  { symbol: 'PDD',   name: 'PDD Holdings' },
  { symbol: 'BIDU',  name: 'Baidu' },
  { symbol: 'NIO',   name: 'NIO' },
  { symbol: 'XPEV',  name: 'XPeng' },
  { symbol: 'LI',    name: 'Li Auto' },
  { symbol: 'RIVN',  name: 'Rivian' },
  { symbol: 'LCID',  name: 'Lucid Motors' },
  { symbol: 'F',     name: 'Ford' },
  { symbol: 'GM',    name: 'General Motors' },
  { symbol: 'STLA',  name: 'Stellantis' },
  { symbol: 'TM',    name: 'Toyota' },
  { symbol: 'HMC',   name: 'Honda' },
  { symbol: 'RACE',  name: 'Ferrari' },
  { symbol: 'MSTR',  name: 'MicroStrategy' },
  { symbol: 'GME',   name: 'GameStop' },
  { symbol: 'AMC',   name: 'AMC Entertainment' },
  { symbol: 'BB',    name: 'BlackBerry' },
  { symbol: 'BBBY',  name: 'Bed Bath & Beyond' },
  { symbol: 'WOLF',  name: 'Wolfspeed' },
  { symbol: 'SMCI',  name: 'Super Micro Computer' },
  { symbol: 'ARM',   name: 'Arm Holdings' },
  { symbol: 'DELL',  name: 'Dell Technologies' },
  { symbol: 'HPQ',   name: 'HP Inc' },
  { symbol: 'HPE',   name: 'Hewlett Packard Enterprise' },
  { symbol: 'IBM',   name: 'IBM' },
  { symbol: 'WDC',   name: 'Western Digital' },
  { symbol: 'STX',   name: 'Seagate' },
  { symbol: 'CSCO',  name: 'Cisco' },
  { symbol: 'ANET',  name: 'Arista Networks' },
  { symbol: 'JNPR',  name: 'Juniper Networks' },
  { symbol: 'GLW',   name: 'Corning' },
  { symbol: 'KEYS',  name: 'Keysight' },
  { symbol: 'MRVL',  name: 'Marvell Technology' },
  { symbol: 'ON',    name: 'ON Semiconductor' },
  { symbol: 'SWKS',  name: 'Skyworks' },
  { symbol: 'QRVO',  name: 'Qorvo' },
  { symbol: 'MPWR',  name: 'Monolithic Power' },
  { symbol: 'ENTG',  name: 'Entegris' },
  { symbol: 'NXPI',  name: 'NXP Semiconductors' },
  { symbol: 'STM',   name: 'STMicroelectronics' },
  { symbol: 'WOLF',  name: 'Wolfspeed' },
  { symbol: 'FSLR',  name: 'First Solar' },
  { symbol: 'ENPH',  name: 'Enphase Energy' },
  { symbol: 'SEDG',  name: 'SolarEdge' },
  { symbol: 'RUN',   name: 'Sunrun' },
  { symbol: 'PLUG',  name: 'Plug Power' },
  { symbol: 'BE',    name: 'Bloom Energy' },
  { symbol: 'NEE',   name: 'NextEra Energy' },
  { symbol: 'PCG',   name: 'PG&E' },
  { symbol: 'SO',    name: 'Southern Company' },
  { symbol: 'DUK',   name: 'Duke Energy' },
]

/** Filter catalog by prefix match on symbol or partial match on name */
export function searchSymbols(query: string, limit = 8): SymbolInfo[] {
  if (!query) return []
  const q = query.toUpperCase()
  const exact: SymbolInfo[] = []
  const prefix: SymbolInfo[] = []
  const contains: SymbolInfo[] = []
  const seen = new Set<string>()

  for (const s of SYMBOL_CATALOG) {
    if (seen.has(s.symbol)) continue
    seen.add(s.symbol)
    if (s.symbol === q) exact.push(s)
    else if (s.symbol.startsWith(q)) prefix.push(s)
    else if (s.name.toUpperCase().includes(q)) contains.push(s)
  }

  return [...exact, ...prefix, ...contains].slice(0, limit)
}
